[package]
name = "generic_levenshtein"
version = "0.1.0"
authors = ["Jerome M. Berger <jeberger@free.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
